### ISSUE TITLE
We need to create maps for the landing page

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#10]
Probably with different thematic views like the different energy grid datasets etc.

**Comment by seabilwe** [comment]
Maps that are in the viewers at the moment:
![image](https://user-images.githubusercontent.com/56301949/114160377-247edc00-9927-11eb-92e2-9e2375116b76.png)

**Comment by dimasciput** [comment]
I don't think we need this anymore since the design of the landing page has changed, I'm closing this ticket.
