### ISSUE TITLE
Maps page needs to clear filter before maps are visible

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#11]
Before pressing clear
![image](https://user-images.githubusercontent.com/178003/114159693-f648ce80-991d-11eb-8612-5a4ce2ae639f.png)

After pressing clear

![image](https://user-images.githubusercontent.com/178003/114159906-3740e300-991e-11eb-8fd6-94055000c0d7.png)

Please make all the maps visible by default on page load

**Comment by dimasciput** [comment]
Fixed by https://github.com/kartoza/clean-cooking-platform/pull/20
