### ISSUE TITLE
High population dense areas not showing in CCE analysis

### ISSUE THREAD

**Issue by camiloramirezgo** [kartoza/clean-cooking-platform#110]
When the population density layer is selected and the analysis tab clicked, the results map is transparent in the dense population areas:
![image](https://user-images.githubusercontent.com/12953752/133401145-5427cc00-3bb2-42a2-94ac-741fe1221176.png)

**Comment by babakkhavari** [comment]
@dimasciput Do you have an update on this issue?

Because 500 is the maximum limit, the population cells with more than 500 people are not shown. Is there a way of determining the limits for the raster datasets from the datasets themselves to avoid this?

**Comment by dimasciput** [comment]
Hi @babakkhavari , I just updated the site, can you check it again and let me know if this is fixed.

**Comment by babakkhavari** [comment]
Population no longer has empty parts and I can see assistance needed index + the clean cooking index.

**Comment by babakkhavari** [comment]
This is fixed
