### ISSUE TITLE
Color ramp of polygon layer not showing on CCE

### ISSUE THREAD

**Issue by camiloramirezgo** [kartoza/clean-cooking-platform#120]
When I add a polygon layer to the CCE, the color ramp style that I have in geo node is not shown:
In CCE:
![image](https://user-images.githubusercontent.com/12953752/135899514-58c05313-7a02-4d1d-a7c3-7f37f963af6d.png)

In GeoNode:
![image](https://user-images.githubusercontent.com/12953752/135899586-793b06c2-0cf9-4c77-b2af-8f05aca2adc8.png)

**Comment by dimasciput** [comment]
this is fixed now
