### ISSUE TITLE
Initial layers to publish on the CCE

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#13]
@dimasciput can you please walk @NyakudyaA through the process of publishing layers on the CCE Tool

@babakkhavari requests these layers are published (would be great to have them online by my call with CCA on thurs):

- Demand
 - Educational facilities
 - GDP
 - Health Facilities
 - Population (HRSL)
 - Wealth index
- Supply
 - HV-network
 - MV-network
 - MG-hydro
 - Substations
- Other
 - Forest cover
 - Roads
 - Solar
 - Traveltime
 - Protected areas

KTH will resample the rasters, will let you know when done

The rasters (GDP, Population, Wealth Index, Forest cover, Solar and travel time) are now all resampled to 1 km in the link
Let me know if there are any issues
@camiloramirezgo  and @babakkhavari  will update metadata during the week

**Comment by dimasciput** [comment]
- Demand
- [x] Educational facilities
- [ ] GDP
- [x] Health Facilities
- [x] Population (HRSL)
- [ ] Wealth index
- Supply
- [ ] HV-network
- [ ] MV-network
- [x] MG-hydro
- [x] Substations
- Other
- [x] Forest cover
- [ ] Roads
- [ ] Solar
- [ ] Traveltime
- [ ] Protected areas

**Comment by babakkhavari** [comment]
Hello @dimasciput 
The Population (HRSL) layer appears under category "Other" on the platform, can it be moved to demand?

**Comment by dimasciput** [comment]
ok done @babakkhavari

**Comment by babakkhavari** [comment]
@timlinux, @dimasciput @NyakudyaA Me an Camilo can not add metadata to the layers on the SDI since we do not have editing rights on the layers can we get editing rights on all layers that are not OSM related?

**Comment by babakkhavari** [comment]
@dimasciput and @timlinux based on dimitris' email it seems they want this list of datasets on the platform. @timlinux do you also interpret his email the same way?

Do you think it makes sense to upload them on the CCE? I am not sure how this process is done and how complicated it is to upload and remove layers from the explorer.

![image](https://user-images.githubusercontent.com/35455877/115505028-27f45a80-a279-11eb-998f-6fc630e9031f.png)
