### ISSUE TITLE
Use updated report templates

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#134]
@dimasciput We have received the revised reports from Maria in 

Nextcloud/Projects/CleanCookingAlliance.org/CleanCookingAlliance-Nepal-Shared/Workshop2-ReportContent/KTH-Mockups

Her revisions are suffixed with 'upd'

![image](https://user-images.githubusercontent.com/178003/137697409-5f097a73-7bf8-4865-9e1e-1265b920c2cc.png)

**Comment by dimasciput** [comment]
The layout has been updated
