### ISSUE TITLE
Landing page typo in first paragraph

### ISSUE THREAD

**Issue by aliciaoberholzer** [kartoza/clean-cooking-platform#135]
On the "Home" page, please make the following change in the second sentence of the first paragraph:

"Approximately 3 billion people depend on polluting open fires or inefficient stoves fueled by kerosene, biomass (wood, animal dung and crop waste) and coal (source: WHO article on household air pollution). "

please make the following change in the last sentence of the first paragraph:

"The household air pollution generated by cooking with polluting fuels and technologies has serious, negative health impacts, with women and children in particular being affected."

**Comment by dimasciput** [comment]
Updated with this ticket https://github.com/kartoza/clean-cooking-platform/issues/166
