### ISSUE TITLE
Report page workflow

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#138]
![image](https://user-images.githubusercontent.com/178003/138056095-990057cc-a481-4e34-8d00-fc297060ec67.png)

1. Move discover use cases button above the map
2. Get rid of subregion boundary if we can automate the activity 
3. Hide country box if only one country available
4. Hide subregion selector when All is chosen (for country level)
5. Change text to Explore this region and make it take you to the explorer tool with all data clipped to the selected region

**Comment by dimasciput** [comment]
this is done
