### ISSUE TITLE
We need to deploy the server on cleancookingexplorer.org

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#14]
@lucernae please provide the IP address of the server and then make sure the site functions normally when accessed via the cleancookingexplorer domain name.

**Comment by lucernae** [comment]
The following address is used:
primary address: `116.202.181.170` (we set it to a floating IP)
The machine IP address is here: `116.203.184.204`

If possible, they need to set both DNS name to point to these address so we have a fallback.
