### ISSUE TITLE
We need a report bread crumb

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#141]
![image](https://user-images.githubusercontent.com/178003/138058059-cddec777-ddf1-41c9-9009-05a92e120948.png)

It should also ideally show you the previous choices made e.g. Province Name, Use Case Name, Scenario Name

Note that those names may be verbose wo we need to find an elegant way to display them without looking cluttered

**Comment by dimasciput** [comment]
this is done
