### ISSUE TITLE
How to remove presets from usercase

### ISSUE THREAD

**Issue by babakkhavari** [kartoza/clean-cooking-platform#144]
How can I remove these presets from a specific usercase?
![image](https://user-images.githubusercontent.com/35455877/139408765-d97c22d6-0a8d-4a70-aeb2-20c184f4ebc1.png)

**Comment by dimasciput** [comment]
@babakkhavari has your question been answered? If so maybe we can close this ticket.

**Comment by babakkhavari** [comment]
Yes, sorry for missing this reply. Will close
