### ISSUE TITLE
Can not find layer to add in the CCE

### ISSUE THREAD

**Issue by babakkhavari** [kartoza/clean-cooking-platform#146]
I added the commercial distance layer and added it to the CCE tool.

Now I am trying to add MV lines as they are needed for one of the story lines. But for some reason it does not appear in the Geonode layer filed 
![image](https://user-images.githubusercontent.com/35455877/139417011-d679f809-79a8-4b00-9528-76168f476f45.png)

The dataset I have uploaded is available here: https://cleancookingexplorer.org/layers/geonode_data:geonode:Existing_MV_lines

I wonder if I am doing something wrong or if I should give it some time?

**Comment by babakkhavari** [comment]
@dimasciput I have another issue with this dataset. 

When I am adding the dataset to the CCE, the entire map turns white and I can not see any of the layers as I select them. As soon as I had the layer, the platform goes back to normal. I can add other datasets without problems. Can you help me with this? I would need this layer up for the storylines

**Comment by babakkhavari** [comment]
So I have been checking a little bit what is happening here. There seems to be something wrong with the coordinate system. I dont know why (it has the correct EPSG and seems to work fine in QGIS)

This is what happens
![image](https://user-images.githubusercontent.com/35455877/140483575-6ca02bca-f743-4110-94b7-338019af1050.png)

1. The dataset does not appear in the supply category
2. The entire map becomes white and it seems to change the extent of the map quite a bit
3. If I select any of the vectors it appears very small in the corner of the canvas

This only happens if the MV lines are "online".

Any ideas of what happen here? @dimasciput @timlinux

**Comment by dimasciput** [comment]
@babakkhavari I have fixed this issue, please test it again, you need to hard refresh first.

**Comment by babakkhavari** [comment]
@dimasciput yes this works now, thanks!
