### ISSUE TITLE
Distances are wrong on the platform

### ISSUE THREAD

**Issue by babakkhavari** [kartoza/clean-cooking-platform#157]
If I select any vector layer that we calculate the distance for (e.g. mini-grid hydro) and go to the analysis tab i can click around on the distance raster to get a pop-up that shows me the distance in every cell to the closest mini-grid hydro. The values shown are wrong. 

![image](https://user-images.githubusercontent.com/35455877/140279881-ad21b5db-09f1-4d06-8fb6-b258ab179290.png)

I assume the distances are read directly from the geonode layers? These distances are in meters so in the image above the distance is not 27459 km, but rather 27.5 km. Can we fix this on the platform, or do we need to re-upload all distance layers with distance directly in km instead?

**Comment by dimasciput** [comment]
Hi @babakkhavari , I think I can fix this on the site. You don't need to reupload the layers.

**Comment by dimasciput** [comment]
@babakkhavari this should be fixed now, please hard refresh first.

**Comment by babakkhavari** [comment]
@dimasciput Great I have tested now and it works! 

But, there still seems to be some differences based on layers (see image)
![image](https://user-images.githubusercontent.com/35455877/140478013-2c2f664a-5c91-454a-b4ac-f6619536e213.png)

For LPG everything seems to be correct. For educational facilities the distance is correct, but can we divide the number by 1000? so that it says 11.2 km instead of 11180 meters? And health facilities do not seem to have changed at all?

These types of problems can be seen with most layers still even after a hard refresh. Would it help if you got a one by one list of which ones are still wrong and which ones are OK?

**Comment by dimasciput** [comment]
@babakkhavari , actually unit is editable from admin page : https://cleancookingexplorer.org/en/admin/custom/category/11/change/
![image](https://user-images.githubusercontent.com/1979569/140479803-d9354cbe-abf7-43bf-abe8-b08718f024af.png)

**Comment by babakkhavari** [comment]
But does that unit do anything? We have always put meter in their, so there should be no reason for it to say km to begin with?

**Comment by dimasciput** [comment]
@babakkhavari I can set meters as default, but maybe this is useful if we want have different unit.

**Comment by babakkhavari** [comment]
Ok, let me know how it goes

**Comment by dimasciput** [comment]
@babakkhavari please try again, you need to do hard refresh first

**Comment by babakkhavari** [comment]
@dimasciput everything except from Planned HV lines seems to work

**Comment by dimasciput** [comment]
@babakkhavar what is the issue?

**Comment by babakkhavari** [comment]
The unit is voltage

**Comment by dimasciput** [comment]
@babakkhavari should be fixed now

**Comment by babakkhavari** [comment]
Yes, this is fixed, thanks! I will close the issue
