### ISSUE TITLE
Layers uploaded are not appearing 

### ISSUE THREAD

**Issue by seabilwe** [kartoza/clean-cooking-platform#16]
@NyakudyaA @dimasciput The layers listed below are not appearing on the GeoNode instance

- https://cca.kartoza.com/layers/GFSAD30SAAFGIRCE_2015:geonode:GFSAD30SAAFGIRCE_2015
- https://cca.kartoza.com/layers/CGIAR_SRTM:geonode:CGIAR_SRTM

@dimasciput This layer https://cca.kartoza.com/layers/geonode_data:geonode:nepal_health_facilities_what3words is showing two legends
![issue 1](https://user-images.githubusercontent.com/56301949/114674417-7ea4e600-9d07-11eb-97c2-4c89db79e2c4.png)

**Comment by NyakudyaA** [comment]
@seabilwe I have fixed those two layers as well, the legend one I haven't bothered to check since I assume Dimas will look at it

**Comment by seabilwe** [comment]
> @seabilwe I have fixed those two layers as well, the legend one I haven't bothered to check since I assume Dimas will look at it

Thanks @NyakudyaA

**Comment by dimasciput** [comment]
Closing this ticket because it has been resolved.
