### ISSUE TITLE
Tool is blank 

### ISSUE THREAD

**Issue by aliciaoberholzer** [kartoza/clean-cooking-platform#167]
When I select a geography and click "Go to Explorer Tool",  the "Data" and "Analysis" tabs are blank
<img width="960" alt="Noload" src="https://user-images.githubusercontent.com/92735518/140979690-9ef53417-9ebf-4bf8-b374-8bab3092fc25.PNG">

.

**Comment by dimasciput** [comment]
Hi @aliciaoberholzer, if you don't want it to be blank, you need to select a use case first. If you go straight to explorer tool from geography, no datasets will be selected.

**Comment by aliciaoberholzer** [comment]
Hi @dimasciput, I know but it should show the selected geography even without having selected any datasets I believe.

**Comment by babakkhavari** [comment]
@aliciaoberholzer is correct. The reason it was blank is due to the MV lines being active (see #146). I have now marked the MV lines as inactive and the platform should work as expected.

**Comment by babakkhavari** [comment]
@dimasciput can issue #146 and #182 please be prioritized? We need these to work for the storylines.

**Comment by dimasciput** [comment]
@babakkhavari @aliciaoberholzer this should be fixed now.

**Comment by babakkhavari** [comment]
Yes, this works now @dimasciput. Thanks!
