### ISSUE TITLE
About page edits

### ISSUE THREAD

**Issue by aliciaoberholzer** [kartoza/clean-cooking-platform#168]
Please make the following changes to text on the "About" page:
1. Change the "A Clean Cooking Platform for Nepal" paragraph to the following:

"Once development is completed in 2021, the CCE will improve data-driven planning, coordination, and implementation for national-scale clean cooking transitions. The CCE will launch with data for Nepal, where CCA, WRI, and a wide range of partners have been engaged with the Alternative Energy Promotion Center (AEPC), the lead government agency promoting clean cooking in Nepal. AEPC is ensuring that the CCE meets the priorities of the Government of Nepal (GoN), providing development support (including assistance with data access and support coordination with key stakeholders) and facilitating with testing and disseminating the CCE among users.

“The Government of Nepal is deeply committed to achieving universal access to clean cooking by 2030,” said Madhusudhan Adhikari, Executive Director of AEPC. “Thanks to tools like the Clean Cooking Explorer, there will be an evidence-based path to accelerating a national transition to clean cooking in Nepal. We are looking forward to working with the team to ensure the CCE is relevant and effective for our clean cooking sector.”

As requested by the GoN, CCA is also developing a Country Action Plan for Transforming the Cookstoves and Fuels Market in Nepal. The CCE will be an important tool in implementing this plan."

2. For each organization, is it possible to provide a link to the organization? In addition, I think we should add a description of each org and what their role in the project is as follows:

Under "Clean Cooking Alliance" change the text to:

"The Clean Cooking Alliance (CCA) works with a global network of partners to build an inclusive industry that can make clean cooking accessible to all. Established in 2010, CCA is driving consumer demand, mobilizing investment, and supporting policies that allow the clean cooking sector to thrive. CCA, in collaboration with the World Resources Institute (WRI) is leading the development of the CCE by leveraging its sector expertise and providing thought leadership."

Under "World Resources Institute" change the text to:

"WRI is a global research organization that works with governments, businesses, multilateral institutions and civil society groups to develop practical solutions that improve people’s lives and protect nature.

“The Clean Cooking Explorer will leverage the power of Geographic Information System (GIS) data and technology combined with stakeholder engagement to provide data-driven insights towards the adoption of clean cooking solutions,” said Dimitrios Mentis, Senior Energy Geographer at WRI and EAE Project Lead. “The CCE will also provide a valuable public good through up-to-date, open-source spatial data repository relevant for policymakers and other stakeholders.”

The CCE will leverage WRI’s experience in the development of the Energy Access Explorer (EAE), while building on CCA’s deep engagement in developing clean cooking markets in Nepal and around the world."

3. Under Implementing Partners, change "the development of the CCE will be supported..." to "The development of the CCE is being supported..."

4. Nepal Open University is misspelled under "Implementing Partners"

5. Add a description for NOU's role in the project, "NOU is the local implementation partner for the CCE. They will provide on-the-ground capacity building opportunities for users. In addition, they will provide ongoing technical support and help ensure platform sustainability."

**Comment by dimasciput** [comment]
Hi @aliciaoberholzer, https://cleancookingexplorer.org/about-us/ has been updated with the new changes.
