### ISSUE TITLE
Landcover image rendering incorrectly

### ISSUE THREAD

**Issue by seabilwe** [kartoza/clean-cooking-platform#17]
@NyakudyaA , the landcover layer https://cca.kartoza.com/layers/MCD12Q1:geonode:MCD12Q1 is rendering incorrectly

Its suppose to render like this:
![image](https://user-images.githubusercontent.com/56301949/114677123-494dc780-9d0a-11eb-9f29-f3d5bf3797e5.png)

But its rendering like this: 
![image](https://user-images.githubusercontent.com/56301949/114677288-713d2b00-9d0a-11eb-97d4-163f1c12a4fe.png)

**Comment by NyakudyaA** [comment]
@seabilwe Here it is https://cca.kartoza.com/layers/MCD12Q1:geonode:MCD12Q1

**Comment by seabilwe** [comment]
Thanks @NyakudyaA
