### ISSUE TITLE
Presets do not honour filter settings

### ISSUE THREAD

**Issue by babakkhavari** [kartoza/clean-cooking-platform#179]
The presets are generated by selecting the correct datasets and the copy-pasting the address in the preset menu in the admin panel.

But, nowhere in the link are filters indicated. E.g. if we select 

- HV lines
- Population 
- Wealth index, filtered to only show poverty above 40 

This is the link we get:   https://cleancookingexplorer.org/tool/?geoId=1&output=eai&view=outputs&inputs=planned-hv-lines%2Cwealth-index%2Cpopulation-of-nepal

If you click on the link above you will see a scenario of 

- HV lines
- Population 
- Wealth index (the entire range)

The filter for Wealth index is not respected.

**Comment by dimasciput** [comment]
@babakkhavari yes currently, the eae tool does not support this, but I will try to implement this feature.

**Comment by dimasciput** [comment]
Hi @babakkhavari , I have implemented this feature now, please try change the filter again and then save the url to preset.

**Comment by babakkhavari** [comment]
Hi @dimasciput, as far as I can see this works for population and the wealth index. Can we please do the same thing for all other datasets in the demand and supply categories as well as Other -> Forest?

**Comment by babakkhavari** [comment]
Fixed.
