### ISSUE TITLE
Unexpected filter behaviour

### ISSUE THREAD

**Issue by babakkhavari** [kartoza/clean-cooking-platform#180]
Filters do not behave as they should.

If I select a dataset and then apply a filter, the filter value that I have changed jumps back to the original value and in order for me to see the filter in effect I have to first uncheck and re-check the layer. 

Example: 

Changing HV-line distance to only show values above 40 km (note that the entire range of distance is still shown in the analysis window):

![image](https://user-images.githubusercontent.com/35455877/141946862-99aff8ed-14b0-45f4-92a7-22d307d06a66.png)

If I uncheck the HV-lines and then recheck it, it gets updated with my filter (but the min value goes back to 0, so you run the risk of loosing track of what you are looking at):

![image](https://user-images.githubusercontent.com/35455877/141947092-ffc57ff6-d246-43ff-8a8e-a091569c0b8f.png)

Let me know if I can perhaps show this clearer.

**Comment by camiloramirezgo** [comment]
This behaviour has already been fixed which is great:

![image](https://user-images.githubusercontent.com/12953752/144461251-cd008235-049c-4297-972e-988dab12e49f.png)
 
However, we have noticed that the slider appears only for new layers that we connect to the CCE tool and not for the ones that were already there before the fix:

![image](https://user-images.githubusercontent.com/12953752/144461531-2501130e-ec8a-4686-b27a-abc3cacaed95.png)

The only way I have found to make this appear is to remove the layer from the CCE in the admin panel and create a new one again with the same characteristics.

@dimasciput is it possible to implement this slider retroactively to the older layers so we don't have to remove and create them again?

**Comment by dimasciput** [comment]
![image](https://user-images.githubusercontent.com/1979569/146891860-1ac7abf4-6d1c-4cf3-a5d7-966b3ce7668c.png)
added now

**Comment by babakkhavari** [comment]
This is fixed now. I had to re-upload the layers to get the filters for other layers. Perhaps this can be made easier?
