### ISSUE TITLE
Calculation of summary counts for education etc for the report

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#188]
Here is the basic logic:

![image](https://user-images.githubusercontent.com/178003/142392569-0d25aa23-b359-477c-a863-751b43c3e76e.png)

And we get at the end the count of schools in high demand areas:

![image](https://user-images.githubusercontent.com/178003/142392818-0e7e0fe8-466d-4838-a654-769ff038119e.png)

**Comment by timlinux** [comment]
[education_in_high_demand.zip](https://github.com/kartoza/clean-cooking-platform/files/7561817/education_in_high_demand.zip)

**Comment by dimasciput** [comment]
I have implemented this.
