### ISSUE TITLE
Style layer changes name automatically

### ISSUE THREAD

**Issue by babakkhavari** [kartoza/clean-cooking-platform#19]
When uploading a new style layer it automatically changes the name of the style to Admin_lvl_0. Why is that? This makes it impossible for us to upload more than one sld as the newest one replaces all previous ones.

**Comment by seabilwe** [comment]
Hi @babakkhavari, usually GeoNode takes the name of the title in the SLD that you are uploading, for example when I upload this style: 
![image](https://user-images.githubusercontent.com/56301949/115741955-7fd1b500-a390-11eb-9cc7-b4282e70c34a.png)

it will take up the name within the file and display it in the legend and as the name of the of the style (as shown below)
![image](https://user-images.githubusercontent.com/56301949/115741762-51ec7080-a390-11eb-861a-41d8caaea28a.png)

In most cases one would go to Editing Tools >> Styles>> Edit and edit the name of the style to a suitable one for the style

**Comment by babakkhavari** [comment]
Hi @seabilwe, 

Yes this I am aware. I managed to get it right with https://cca.kartoza.com/layers/ByteTest:geonode:ByteTest after some tries. But I forgot what I changed. I think it had to do with the type of the dataset (I changed the type to Byte when exporting the layer and reuploaded the dataset). Maybe we can keep this open and I will let you know if I am still experiencing problems for the rest.

**Comment by seabilwe** [comment]
Okay @babakkhavari we can leave it open

**Comment by babakkhavari** [comment]
@seabilwe as an example currently I am trying to upload a style for this layer https://cca.kartoza.com/layers/geonode:GFSAD30SAAFGIRCE_2015 

But it gives me the wrong name and the old legend. File looks like this. Do you know why this does not work?
![image](https://user-images.githubusercontent.com/35455877/115830424-915aa180-a410-11eb-9cb2-bea74fe59e24.png)

**Comment by babakkhavari** [comment]
Same thing here: https://cca.kartoza.com/layers/CGIAR_SRTM:geonode:CGIAR_SRTM
It changes the name of my style to Admin_lvl_0, but if you download the .sld with the same name it says 
![image](https://user-images.githubusercontent.com/35455877/115832557-4f7f2a80-a413-11eb-9091-db1151bb6de2.png)

**Comment by seabilwe** [comment]
@babakkhavari please check the style again, I changed the name of the style
![image](https://user-images.githubusercontent.com/56301949/115876896-25dff680-a447-11eb-9f96-5dac8cb1f33d.png)

**Comment by seabilwe** [comment]
@NyakudyaA This layer for example https://cca.kartoza.com/layers/CGIAR_SRTM:geonode:CGIAR_SRTM, the style that @babakkhavari had uploaded, took the name of one of the admin layers, not sure if its a bug, but I had to change the name in Geoserver. Its mostly when uploading styles for rasters, haven't noticed that for vectors
