### ISSUE TITLE
In subnational results the areas with the highest potential are excluded.

### ISSUE THREAD

**Issue by babakkhavari** [kartoza/clean-cooking-platform#191]
How it looks in data view, the red is high population density and the blue lines are MV-lines, we would therefore expect the Energy access potential to be the highest possible here.
 
![image](https://user-images.githubusercontent.com/35455877/142452462-1a696def-4d96-4ab9-ae25-440c8e71bea6.png)

But this is how it looks in the analysis view, the cells overlaid with MV lines are now gone (the city called Pokhara)  
![image](https://user-images.githubusercontent.com/35455877/142452716-768843a7-1544-4932-9745-ed4f07906f76.png)

**Comment by dimasciput** [comment]
@babakkhavari can you try it again please, I think I fixed this.

**Comment by babakkhavari** [comment]
@dimasciput I seem to have this issue.

**Comment by dimasciput** [comment]
Hi @babakkhavari , can you share the link?

**Comment by babakkhavari** [comment]
@dimasciput 
https://cleancookingexplorer.org/tool/?boundary=4009c6c2-6787-3371-951f-b2716139e4d9&geoId=1&output=supply&view=outputs&inputs=existent-hv-lines%2Cpopulation-of-nepal

**Comment by dimasciput** [comment]
Hi @babakkhavari, this is because the layer have the same value for the highest and nodata which is 0. Or maybe the nodata value has not been set.
@timlinux can we update these layers for now?

**Comment by babakkhavari** [comment]
Thank you @dimasciput. 

I guess the reason this worked fine in the national scenarios but not sub-national is because you mask the sub-national datasets?

When you mask on the platform can you assign another value as no-data?

**Comment by timlinux** [comment]
tradition would be to us -9999.0  for no data

**Comment by timlinux** [comment]
Ok on further reflection using -9999 would be a bad idea since our client software will probably blindly add the cell values.


We can see from 

```
wget -O mv-lines-subnational.tiff "https://cleancookingexplorer.org/uploaded//clipped/geonode:Existent_MV_lines_dist:4009c6c2-6787-3371-951f-b2716139e4d9/Existent_MV_lines_dist.tif"
```

That the resulting clipped layer has 0 for where the lines should be and 0 for no data,

![image](https://user-images.githubusercontent.com/178003/144444075-0b38c8cb-54b8-4701-94ee-f9b0ddec3f65.png)

Maybe if we cannot properly assign null to the wcs clipped data we can assign the lines a very small value (e.g. <1 m). Ideally the wcs extract should assign NAN to the nodata cells and 0 to the lines.

![image](https://user-images.githubusercontent.com/178003/144443781-78f0b5c8-e41d-4e85-bc7f-7c1411ebf745.png)

**Comment by timlinux** [comment]
See also https://gis.stackexchange.com/questions/172236/geoserver-altering-raster-values-of-multi-band-raster-wcs-request

**Comment by dimasciput** [comment]
@timlinux https://cleancookingexplorer.org/geoserver/wcs?service=WCS&request=GetCoverage&coverageid=geonode__traveltime_to_urban_by_road&format=image/tiff&version=2.0.1&srs=EPSG:4326&bbox=80.0666667,26.3500000,88.2000000,30.4416667&SCALESIZE=i(975.0),j(490.0)

**Comment by dimasciput** [comment]
https://cleancookingexplorer.org/geoserver/wcs?service=WCS&request=GetCoverage&coverageid=geonode__population_npl_2018_10_01&format=image/tiff&version=2.0.1&srs=EPSG:4326&bbox=8912499.9999830,3041738.2621151,9818499.9999830,3560738.2621151&SCALESIZE=i(975.0),j(490.0)

**Comment by timlinux** [comment]
Discussed in our call today  and for now we need to address it by tweaking the data - assign a very low non zero value to the affected cells.

**Comment by babakkhavari** [comment]
@dimasciput @timlinux, this has now been done but the issue still persists. 

Check the following [dataset](https://cleancookingexplorer.org/layers/Existent_HV_lines_dist:geonode:Existent_HV_lines_dist)
The no-data value is set to a very small number, but when checking the sub-national scenarios high potential areas are still removed.

**Comment by babakkhavari** [comment]
Ignore the previous message, I think I might have solved the issue, will keep you posted on how it goes.

**Comment by babakkhavari** [comment]
This is now fixed.
