### ISSUE TITLE
Calculation for summary report (Urban ratio, proverty, pollution)

### ISSUE THREAD

**Issue by dimasciput** [kartoza/clean-cooking-platform#203]
Hi @babakkhavari,

Do you know how to calculate these three points from the report: 
![image](https://user-images.githubusercontent.com/1979569/143343022-eb0c8388-471c-4496-bfd4-8fbe7036d98d.png)

**Comment by babakkhavari** [comment]
Hi @dimasciput,

1. For urban coverage use this: https://cleancookingexplorer.org/layers/urban_rural_Nepal:geonode:urban_rural_Nepal

This layer would have to be used with population. It is only a classification at the moment. All values above 20 we usually define as urban. Maybe we can start like that and see if we have to adjust.
 
2.  Population relying on polluting fuels you can find here: https://cleancookingexplorer.org/layers/geonode_data:geonode:Traditional 

Please use this even for the sub-national analysis (I know the dissagregation is lower than what we allow for subnational studies, but this is the best we have. 

3. For poverty you can use: https://cleancookingexplorer.org/layers/Wealth_index_2011:geonode:Wealth_index_2011

You should use this together with population to create a weighted average of how many are poor. You can use all values in the International Wealth Index less than 50. I do not know what will be simplest for you, but I could mask out all non-poor people and then you can clip population in the by this raster?

**Comment by dimasciput** [comment]
this is done
