### ISSUE TITLE
Error opening province explorer tool

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#223]
![image](https://user-images.githubusercontent.com/178003/144270890-934092ad-23b4-4ba8-9e54-db563a49b8cb.png)

https://cleancookingexplorer.org/tool/?boundary=038580c8-abfb-3131-8fd3-b98408b5b243&geoId=1&output=eai

To Replicate:
![error](https://user-images.githubusercontent.com/178003/144271178-d45761c6-e4ee-43cf-9310-7ad214d41aab.gif)

**Comment by timlinux** [comment]
Seems we get the error also for reports at province level. District works

**Comment by dimasciput** [comment]
this is fixed https://cleancookingexplorer.org/tool/?output=eai&view=inputs&inputs=medium-voltage-lines%2Cmini-grid-hydropower%2Cwealth-index%2Cpopulation-of-nepal%2Chealth-facilities%2Ceducation-facilities&boundary=cf95b33d-7531-3f8e-b21a-19d9932769a9&geoId=1
