### ISSUE TITLE
No health and edu on report

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#229]
![image](https://user-images.githubusercontent.com/178003/144449120-54debbb4-5c63-4220-8d1f-827a9904010f.png)

Maybe it relates to #191

**Comment by dimasciput** [comment]
@timlinux you need to add this category per preset in the admin page.

**Comment by dimasciput** [comment]
https://cleancookingexplorer.org/en/admin/custom/summaryreportcategory/
