### ISSUE TITLE
Reports still use the incorrect templates

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#230]
@babakkhavari please attach them here, @dimasciput please review and adjust the reports accordingly.

**Comment by babakkhavari** [comment]
These should be the latest ones 

[Integrated planning upd.pptx](https://github.com/kartoza/clean-cooking-platform/files/7643697/Integrated.planning.upd.pptx)
[Investors scenario 1 upd.pptx](https://github.com/kartoza/clean-cooking-platform/files/7643698/Investors.scenario.1.upd.pptx)
[Investors scenario 2 upd.pptx](https://github.com/kartoza/clean-cooking-platform/files/7643699/Investors.scenario.2.upd.pptx)
[Policy makers scenario 1 upd.pptx](https://github.com/kartoza/clean-cooking-platform/files/7643700/Policy.makers.scenario.1.upd.pptx)
[Policy makers scenario 2 upd .pptx](https://github.com/kartoza/clean-cooking-platform/files/7643701/Policy.makers.scenario.2.upd.pptx)
[Policy makers scenario 3 upd.pptx](https://github.com/kartoza/clean-cooking-platform/files/7643702/Policy.makers.scenario.3.upd.pptx)
[Policy makers scenario 4 upd.pptx](https://github.com/kartoza/clean-cooking-platform/files/7643703/Policy.makers.scenario.4.upd.pptx)
