### ISSUE TITLE
Reports never generate

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#231]
![image](https://user-images.githubusercontent.com/178003/144450205-c39096d2-cfe8-4da6-ba15-49c8a9190c54.png)

**Comment by dimasciput** [comment]
This is because of the boundary is not generated. so same issues with https://github.com/kartoza/clean-cooking-platform/issues/223

**Comment by dimasciput** [comment]
also fixed 
![image](https://user-images.githubusercontent.com/1979569/144555526-392121f7-d012-42bf-b5c6-f6245383d52f.png)
