### ISSUE TITLE
Setup training server

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#257]
@dimasciput and @lucernae for the CCE we are going to be running training in feb
Can you please set up a staging instance that we can use as a sandbox for the training sessions
Then pull it down at the end of feb

**Comment by lucernae** [comment]
@dominicschaff and I need more info for this.
Do we spin up identical instance with zero data or also identical data?

**Comment by lucernae** [comment]
@Tim @dimasciput do you have URL name already for this CCA training? We might have to create migration script to replace URL of cleancookingexplorer.org into this training server?

**Comment by dimasciput** [comment]
@timlinux do we have the URL ready for this?

**Comment by dominicschaff** [comment]
The training instance was completed last week, with data migration completing end of last week
