### ISSUE TITLE
Full country analysis fails

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#285]
![image](https://user-images.githubusercontent.com/178003/149780405-40af126d-df17-4450-95c9-569289138640.png)

**Comment by timlinux** [comment]
I tested again and it works now - I guess it was clipping the first time around. Maybe we need a better way to manage wait states for the user if it is clipping the first time?

**Comment by dimasciput** [comment]
this is a bug actually, and it should be fixed now.
