### ISSUE TITLE
Minimum and Maximum colours on International Wealth Index colour ramp are the same

### ISSUE THREAD

**Issue by LesegoMohaule** [kartoza/clean-cooking-platform#292]
![image](https://user-images.githubusercontent.com/69116236/150076770-61cad964-fba7-40da-86da-732c04b01fde.png)

**Comment by babakkhavari** [comment]
This is now fixed

![image](https://user-images.githubusercontent.com/35455877/152551367-f2bde3d0-cbfb-4e7f-a62e-84745cfb22c4.png)
