### ISSUE TITLE
Analysis report generated does not show the analysis information on the website

### ISSUE THREAD

**Issue by LesegoMohaule** [kartoza/clean-cooking-platform#294]
[How can the tool help investors_-Investors focusing on LPG-Nepal.pdf](https://github.com/kartoza/clean-cooking-platform/files/7894755/How.can.the.tool.help.investors_-Investors.focusing.on.LPG-Nepal.pdf)

**Comment by dimasciput** [comment]
Yes we need to configure the analysis information from the admin page.

**Comment by dimasciput** [comment]
For now you can test this preset : 
![image](https://user-images.githubusercontent.com/1979569/150081867-d9aae1d4-d59c-4f08-8dec-10aea5e81790.png)

**Comment by LesegoMohaule** [comment]
I do not have admin permissions. The option of Policy maker focusing on
electricity does not appear when I open CCE.
