### ISSUE TITLE
Fix phrasing for health facilities in report

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#299]
![image](https://user-images.githubusercontent.com/178003/150100307-e662f3f2-f2dd-45c8-b330-65351016a45e.png)

@babakkhavari can you change this in the admin please to read:

"Health facilities close to supply"

**Comment by babakkhavari** [comment]
Yes, I will make sure it is removed when we start doing the reports. This is based on what I type for each index in the admin panel.
