### ISSUE TITLE
We need to prototype integration between WRI and GeoNode

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#3]
We want to support the workflow where layers in the explorer are fetched from GeoNode and no need for MapBox subscription etc.

![image](https://user-images.githubusercontent.com/178003/112299761-057a1c00-8c90-11eb-982a-181028ba5c0c.png)

**Comment by timlinux** [comment]
Ideally metadata should come from GeoNode / GeoServer too:

![image](https://user-images.githubusercontent.com/178003/112300110-6b66a380-8c90-11eb-9475-91c74b794a78.png)


![image](https://user-images.githubusercontent.com/178003/112300289-9650f780-8c90-11eb-93e6-c15dfe8bd4de.png)


We need to establish the workflow to preprocess the layers so that they are all 0-1 value range (this can be done manually by the user) and perhaps use metadata or other mechanism.

Also we should support general GIS layers being pulled in to the 'other' section e.g.

![image](https://user-images.githubusercontent.com/178003/112300569-e3cd6480-8c90-11eb-9563-8d9a7e7f3208.png)


These are not scaled from 0-1

**Comment by timlinux** [comment]
For Analysis layers, they are scaled to percentiles and have the toggle advanced controls

![image](https://user-images.githubusercontent.com/178003/112301203-98678600-8c91-11eb-9c80-c1d4e828c642.png)

For static layers they have no toggle advanced controls or percentile slider etc.

When a layer is uploaded to GeoNode, we will need to tag the layer with one of these categories:

![image](https://user-images.githubusercontent.com/178003/112301727-27749e00-8c92-11eb-94b3-9141b9601160.png)

And then use GetCapabilities etc to discover the layers and put them into the WRI

**Comment by timlinux** [comment]
Additionally, we should fetch from GeoNode the geography for which the layer applies so that we can provide an experience where you choose a country and then see only layers from that country:

![image](https://user-images.githubusercontent.com/178003/112302089-94883380-8c92-11eb-8526-03a0c2ac30ee.png)

![image](https://user-images.githubusercontent.com/178003/112302181-b1246b80-8c92-11eb-81e2-fa4c05f0a3fb.png)

**Comment by timlinux** [comment]
Note also that some layer types may not be percentil, but distance or other productivity measures:

![image](https://user-images.githubusercontent.com/178003/112302668-3d369300-8c93-11eb-9d03-bf329873d458.png)

**Comment by dimasciput** [comment]
this is done
