### ISSUE TITLE
Cost ebenfit layer filters not working

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#307]
![filters](https://user-images.githubusercontent.com/178003/150368894-8bf3be5c-89bd-45fd-89e1-e7f09dba950b.gif)

**Comment by timlinux** [comment]
The regions in colour should shrink / grow when the slider is moved

**Comment by dimasciput** [comment]
@timlinux this only works if you analysis layer selected, and you can only see the changes in the analysis mode.

**Comment by babakkhavari** [comment]
Additionally the datasets, when connecting them from the geonode to the CCE, need to be indicated as inclusion buffers. We will upload the new layers this week and make sure that inclusion buffer is selected. This should fix this issue.

**Comment by babakkhavari** [comment]
This is fixed.
