### ISSUE TITLE
Update the methodology page

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#308]
![image](https://user-images.githubusercontent.com/178003/150374047-4688f3c1-2ada-46ca-a2ea-61b3b8b44fdb.png)

Then take the slide deck from Alicia and add the content from the numbered slides to the methodology page

**Comment by timlinux** [comment]
These are the slides we want to incorporate - I think we can remove the other diagrams for now

Slide 6

Slide 7

Slide 21

Slide 23

Slide 25

Slide 27
[CCE datasets validation v2 (1).pptx](https://github.com/kartoza/clean-cooking-platform/files/7906821/CCE.datasets.validation.v2.1.pptx)

**Comment by dimasciput** [comment]
@timlinux updated here https://cleancookingexplorer.org/methodology/
