### ISSUE TITLE
CCE Training Module 4: Energy access potential raster not appearing

### ISSUE THREAD

**Issue by LesegoMohaule** [kartoza/clean-cooking-platform#310]
Existing MV lines distance (Raster) does not show as in the training manual after it has been added and saved
![image](https://user-images.githubusercontent.com/69116236/150493925-bc0cc01d-c9f3-4e0e-93a6-5f8b33911788.png)

**Comment by dimasciput** [comment]
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/1979569/150495304-d3442500-9bd8-4270-9b55-2de0f0fa012d.png">

It's because there are two categories with the same name, I removed one of them and it should works now.
