### ISSUE TITLE
CCE Training Module 4: New use case not appearing in CCE tool>Discover use cases

### ISSUE THREAD

**Issue by LesegoMohaule** [kartoza/clean-cooking-platform#311]
After new test use case has been created and saved under Admin, it does not appear in CCE tool under Discover use cases
![image](https://user-images.githubusercontent.com/69116236/150499431-82e913f2-a479-4ad7-9e2d-0052a42a0be2.png)

**Comment by dimasciput** [comment]
@LesegoMohaule you need to set the geography to Nepal
