### ISSUE TITLE
Province 1 do not get any indices even with datasets selected

### ISSUE THREAD

**Issue by babakkhavari** [kartoza/clean-cooking-platform#320]
I am adding datasets here, but nothing happens with regards to indices. 

https://cleancookingexplorer.org/tool/?boundary=bdea4847-7ad1-359e-b31d-28bae8b588dc&geoId=1&output=eai&view=inputs&inputs=

See image below. I have selected educational facilities so I should have a demand index. This is just an example we have the same problem with all datasets.
![image](https://user-images.githubusercontent.com/35455877/152511495-a8a79e37-9747-4c46-813d-edaabe6d7735.png)

**Comment by dimasciput** [comment]
@babakkhavari forget my last comment, I think it's a different issue, will check it next week.

**Comment by babakkhavari** [comment]
Looking into this a bit more, it seems like no rasters show in province 1 (see image). 
![image](https://user-images.githubusercontent.com/35455877/153206747-4f709740-1363-46d1-b93e-a02c13bde129.png)
