### ISSUE TITLE
Clean up metadata

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#322]
![imagem](https://user-images.githubusercontent.com/178003/153017162-f9986e3e-16bd-4af5-b07a-a6cc12f78519.png)

NOU / KTH - can we standardise the metadata to include content similar to the EAE below

![imagem](https://user-images.githubusercontent.com/178003/153017202-35aa6194-e09a-4495-874f-8fb2dd0cc8ab.png)

@dimasciput can you give the metadata view a bit of live? Remove extraneous fields and clean up the presentation a little?

**Comment by aliciaoberholzer** [comment]
It would be nice if our metadata could be presented the same as the EAE's (Tim's second screenshot) @babakkhavari @camiloramirezgo @dimasciput

**Comment by timlinux** [comment]
For the citations we can capture them in the same form as the EAE 

"[1] Kenya National Bureau of Statistics (KNBS). 2019 Kenya Population and Housing Census Volume IV: Distribution of Population by Socio-Economic Characteristics. Accessed Through Energy Access Explorer, [date]. www.energyaccessexplorer.org.

**Comment by babakkhavari** [comment]
@dimasciput, @timlinux, @aliciaoberholzer are we going to change the metadata to look like it does in the EAE?

If so, I will wait with updating the metadata for the datasets until after this is done (unless the information can be transferred from the old template to the new one?)

I suggest we fill in the sections of the metadata from the following sections of the metadata wizard :
Description taken from Abstract
Suggested Citation taken from Supplementary information
Cautions from Data quality statement
Sources from Attribution
Spatial Resolution from Regions
Date of content from the four first numbers of Date
Links from  DOI

Also all layers now have:

"[1] Kenya National Bureau of Statistics (KNBS). 2019 Kenya Population and Housing Census Volume IV: Distribution of Population by Socio-Economic Characteristics. Accessed Through Energy Access Explorer, [date]. [www.energyaccessexplorer.org](http://www.energyaccessexplorer.org/)."

as suggested citation, please remove.
