### ISSUE TITLE
Data quality statement

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#324]
@aliciaoberholzer can you add details here. And where it should be shown.

**Comment by aliciaoberholzer** [comment]
Can you please add the following statement to both the methodology page (at the end), as well as in the reports?

"The Clean Cooking Explorer adheres to the data quality standards set in place by WRI's Energy Access Explorer (EAE). To view more information about data quality standards, view the [technical note](https://files.wri.org/d8/s3fs-public/energy-access-explorer-data-and-methods.pdf)."
