### ISSUE TITLE
We need to check the boundaries and produced generated against those boundaries

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#325]
From Dilip:

> Dear Tim,
> As mentioned, please find attached the two maps (wrong – as appeared in the explorer and right one).
> Best, Dilip

@camiloramirezgo @babakkhavari @bgmishra could you investigate this and come up with an action plan for if all the input layers are clipped to an incorrect boundary? Could you confirm if all our layers are clipped to this, or if it is just an issue with the boundary itself?

![incorrect](htt

ps://user-images.githubusercontent.com/178003/153020200-10d204ad-0455-4e9a-9e39-b7f7f01f9c02.PNG)
![incorrect and correct](https://user-images.githubusercontent.com/178003/153020207-3cfb4d81-0cbb-4bde-89e0-584cd00931bf.PNG)
![correct](https://user-images.githubusercontent.com/178003/153020210-6de8a76b-98a8-4b6d-a495-1bcc9ea98384.PNG)
![correct one](https://user-images.githubusercontent.com/178003/153020213-33b620e4-58ad-4a3f-af02-5d69dbafa37e.png)
![not correct](https://user-images.githubusercontent.com/178003/153020214-10da9c42-ad6e-4607-97c5-aeb7018dd77e.png)

**Comment by babakkhavari** [comment]
None of the vector layers that are on the platform have been clipped as far as I know. There distance maps are also created with the map the same boundaries as here: https://cleancookingexplorer.org/layers/geonode_data:geonode:NPL_adm0_Nepal0 . This map looks like your third map @timlinux 

![image](https://user-images.githubusercontent.com/35455877/153364330-51252a1b-9be1-47cd-96e0-e8877fff6593.png)

Note that certain vectors (health and educational facilities) do not have anything in the "new" part, but this is also true for the original dataset. I want to double check the health facility distance however.

**Comment by babakkhavari** [comment]
For rasters:

- GDP I think is easily solved by just reclipping it
- The International Wealth Index is from Facebook. The borders are predefined (i.e. the dataset for Nepal looks the same way it does on the platform. We can extend it if you want, but this would then be either a simple interpolation/just giving all areas in the "new" part 0?

**Comment by babakkhavari** [comment]
The datasets have been fixed and unless anyone else has any comments it can be closed @timlinux

**Comment by timlinux** [comment]
Thanks @babakkhavari

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/154505141-58c3ade3-9bca-4e27-a104-88cbdab4908a.png)


@dimasciput can you set the new admin boundaries to be used in the frontend please?

**Comment by babakkhavari** [comment]
This is fixed.
