### ISSUE TITLE
Report never loads

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#333]
![image](https://user-images.githubusercontent.com/178003/154285021-ea03d479-5261-48a1-8139-42ab4afa53d0.png)

https://cleancookingexplorer.org/tool/?boundary=682790ff-0f31-311e-af9f-1fa3a0100caf&geoId=1&output=eai&view=outputs&inputs=electrification-percentage

**Comment by dimasciput** [comment]
@timlinux to generate a report first you need to select use case and the scenario, if not this should open the default pdf from the energyaccessexplorer.

**Comment by timlinux** [comment]
In my case I picked a region and then went to the explorer tool and then clicked the report button.

**Comment by dimasciput** [comment]
this is resolved now

**Comment by babakkhavari** [comment]
I do not think this is fixed. I am trying to load the report for integrated planning. It is taking never loads @dimasciput

**Comment by dimasciput** [comment]
@babakkhavari can you send me the link?

**Comment by dimasciput** [comment]
@babakkhavari this should be resolved now, please try it again
