### ISSUE TITLE
Download Report ( Map and chart not visible)

### ISSUE THREAD

**Issue by brghimire** [kartoza/clean-cooking-platform#338]
![image](https://user-images.githubusercontent.com/10744061/155002798-f3729367-b38d-42e6-aeca-510219d1a7cb.png)

![image](https://user-images.githubusercontent.com/10744061/155003010-b94a603d-a734-4fa3-bf07-e7b8e87ac7ec.png)

I thought we had a chart and map in the report template.

**Comment by brghimire** [comment]
Exploring more I found that this has been included in the TTest Use Case 2>utorial Preset .
I wish this could be available in other reports as well.
@dimasciput

**Comment by dimasciput** [comment]
@brghimire yes you need to add that in the admin page for each presets, this couldn't be done automatically.
