### ISSUE TITLE
Table on the first page is missing information. 

### ISSUE THREAD

**Issue by babakkhavari** [kartoza/clean-cooking-platform#347]
![image](https://user-images.githubusercontent.com/35455877/155306873-4481ac79-7dd1-495d-b0b6-b7e3432c45a0.png)

**Comment by timlinux** [comment]
![imagem](https://user-images.githubusercontent.com/178003/157206275-cbf3436a-fac9-4cf0-9684-6c287bb3e8cf.png)

**Comment by dimasciput** [comment]
It is fixed now
