### ISSUE TITLE
EAE reference in Methodology

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#355]
In the methodology page, I ‘d bring up to the main CCE box the sentence “CCE builds on the methods introduced by and the open-source technology
developed for WRI’s Energy Access Explorer (EAE).” add a link to EAE’s Technical Note: https://www.wri.org/research/energy-access-explorer-data-and-methods

**Comment by dimasciput** [comment]
We have this in the methodology I think, but just in different wording.
