### ISSUE TITLE
Change text on landing page

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#357]
"The spatial platform integrates and supports analysis of geospatial datasets related to both the potential demand and supply of clean cooking services, allowing for data-driven planning, coordination, and decision-making to support the uptake and adoption of clean cooking. This platform empowers users to visualize, interpret, and analyze geospatial datasets to accelerate access to clean cooking. "

To

"The platform enables data-driven planning, coordination, and decision-making by integrating and supporting analysis of geospatial datasets related to both the potential demand and supply of clean cooking services, to support the uptake and adoption of clean cooking in the study area".

**Comment by dimasciput** [comment]
updated
