### ISSUE TITLE
Better landing page pic

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#359]
Can you share some options for the landing page image and then @dimasciput please update the site

**Comment by aliciaoberholzer** [comment]
We could use Nepal photos from Pexel: https://www.pexels.com/search/nepal/. I attached one of cooking in Nepal specifically as well.
![IMG_20190913_133129](https://user-images.githubusercontent.com/92735518/156660212-961e1465-ecf4-432e-944d-cce6f20cd7b6.jpg)

**Comment by dimasciput** [comment]
@aliciaoberholzer that's a lot pictures, can you point out which picture to use? I think we just need one.

**Comment by aliciaoberholzer** [comment]
I like this one: https://drive.google.com/file/d/1t0aT2fnT24-PyccGTj3LzGpIxmzZfKVH/view?usp=sharing
