### ISSUE TITLE
Provide reference link for quote

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#361]
![imagem](https://user-images.githubusercontent.com/178003/156406256-2d421a71-7c1c-4760-889a-dbefb91f6796.png)

@alicia to share the link here

**Comment by aliciaoberholzer** [comment]
https://www.who.int/news-room/fact-sheets/detail/household-air-pollution-and-health

**Comment by aliciaoberholzer** [comment]
We could use Nepal photos from Pexel: https://www.pexels.com/search/nepal/. I attached one of cooking in Nepal specifically as well. 

![IMG_20190913_133129](https://user-images.githubusercontent.com/92735518/156660027-375be54c-dce4-41f0-8491-2ca006c74dcc.jpg)

**Comment by dimasciput** [comment]
updated with the link
