### ISSUE TITLE
Inconsistencies in populaion across the reports

### ISSUE THREAD

**Issue by babakkhavari** [kartoza/clean-cooking-platform#372]
The population value in the table of the first page

![image](https://user-images.githubusercontent.com/35455877/157221108-930bd6d6-467a-4a6d-9d2c-88f81ef48030.png)

and the population in the calculations

![image](https://user-images.githubusercontent.com/35455877/157221771-c2560500-f9af-4852-9e9e-1d18e8a0097c.png)

do not match. Ensure that the same calculations are used for each one of these numbers so that we have consistency in the reports.

The screenshots are from the national analysis, preset: policy makers focusing on LPG. But I think this error should also exist in all other storylines.

**Comment by dimasciput** [comment]
Make sure to use the ANI layer with medium to index.

**Comment by dimasciput** [comment]
This is fixed by unchecking the invert option for ANI analysis in the admin 
![image](https://user-images.githubusercontent.com/1979569/158979220-f4a677fe-79f6-409e-9496-c39275c76f14.png)
