### ISSUE TITLE
Do we want to respecify Admin boundary in datasets

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#39]
Currently there is some duplication since we set up the geography with Vector and Raster boundary (See #38 ) and then in the datasets UI we again declare the Admin boundary, this time also adding a CSV with population data. No action for now but perhaps we can define the admin only once in geography and then have it automatically added to Datasets / the CCE UI.

![image](https://user-images.githubusercontent.com/178003/118465769-1ed09f00-b6fa-11eb-872e-c4cbc185e618.png)

**Comment by dimasciput** [comment]
We don't need to add boundaries dataset anymore
