### ISSUE TITLE
Raster transparency not respected when using the CCE

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#80]
Works in GeoNode:

https://cleancookingexplorer.org/maps/new?layer=geonode:Traveltime_forest_hr0&view=True

![image](https://user-images.githubusercontent.com/178003/123079484-e700f980-d413-11eb-8017-55a249cd8063.png)

But in the tool:

![image](https://user-images.githubusercontent.com/178003/123079672-10218a00-d414-11eb-918a-57ff6de10f7a.png)

**Comment by camiloramirezgo** [comment]
@dimasciput @timlinux this is still an issue, is there something that we can do from our side? maybe related to the NaNs value that we should use, or should we provide a mask layer?

**Comment by dimasciput** [comment]
Hi @camiloramirezgo , let me try to resolve this issue first from my side. Will let you know if I need some help from your side.

**Comment by dimasciput** [comment]
@camiloramirezgo @timlinux this has been fixed.
