### ISSUE TITLE
CCE froze after adding new layer

### ISSUE THREAD

**Issue by camiloramirezgo** [kartoza/clean-cooking-platform#81]
The CCE is no longer loading after I added a new layer from GeoNode. I had uploaded several layers before without a problem, but now the CCE does not load anymore: 
![image](https://user-images.githubusercontent.com/12953752/124471979-da7a8a80-dd9d-11eb-82fb-ae3babd01eac.png)
I deactivated the new layer to check if that was causing the problem, but the behaviour is the same. This had happened before to me on another occasion.

**Comment by dimasciput** [comment]
this should be resolved by now
