### ISSUE TITLE
Unable to upload datasets to geonode

### ISSUE THREAD

**Issue by babakkhavari** [kartoza/clean-cooking-platform#92]
When attempting to upload datasets to the geonode I get an error message reading "Import Session is Invalid!"

![image](https://user-images.githubusercontent.com/35455877/130579780-7f7950fc-e0be-4ae7-9344-d26fd2780103.png)

**Comment by dimasciput** [comment]
Hi @babakkhavari try hard refresh your browser and then reupload your datasets. Or use different browser.

**Comment by babakkhavari** [comment]
Hello @dimasciput, I get the same problem with hard refreshed browser and when I do it both on Firefox and Chrome

**Comment by dimasciput** [comment]
@babakkhavari can you try login with the cce-admin? I just tested it with cce-admin, and it worked.

**Comment by babakkhavari** [comment]
Is it the same username/password as we previously used to get access to the site?

**Comment by babakkhavari** [comment]
No I get the same problem with the cce-admin, so I guess the problem is on my side

**Comment by dimasciput** [comment]
Is it also the same with different layers @babakkhavari ?

**Comment by babakkhavari** [comment]
Yes

**Comment by babakkhavari** [comment]
So if I convert to GeoJSON it works. Camilo seems to have the same problem. @dimasciput, when you tried did you upload a shapefile or GeoJSON?

**Comment by dimasciput** [comment]
@babakkhavari I tried with shapefile and tiff files. Let me check it again today.

**Comment by babakkhavari** [comment]
Will close this, does seem to only be specific to one dataset
