### ISSUE TITLE
Error with some layers when opening tool

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#94]
![image](https://user-images.githubusercontent.com/178003/130760708-ee51625f-1e20-4d49-a750-26cf03e00b81.png)

**Comment by dimasciput** [comment]
@timlinux it's because there are no layers associated with the dataset. Maybe we should disable those datasets for now?

**Comment by dimasciput** [comment]
the dataset will not be published if it is invalid.
