### ISSUE TITLE
About page updates

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#97]
![TimCCEWireFrames-About](https://user-images.githubusercontent.com/178003/131808609-eb7d64f9-44b7-4c2f-81cc-80a1cda8bbd1.png)

[TimCCEWireFrames.zip](https://github.com/kartoza/clean-cooking-platform/files/7097299/TimCCEWireFrames.zip)

Please use latest CCE style

**Comment by timlinux** [comment]
In each org, also include the bio pic and profile of the associated people.

CCA: Anobha and Alicia
WRI: Dimitrios and Santiago
KTH: Francesco, Camilo, Babak, Dilip
Kartoza: Tim, Dimas, Lindsay
NOU: Mishra and Bhoj

**Comment by dimasciput** [comment]
this is done
