### ISSUE TITLE
Update site experience

### ISSUE THREAD

**Issue by timlinux** [kartoza/clean-cooking-platform#99]
[TimCCEWireFrames.zip](https://github.com/kartoza/clean-cooking-platform/files/7097532/TimCCEWireFrames.zip)

**Comment by timlinux** [comment]
Should have LAF of 
![image](https://user-images.githubusercontent.com/178003/131814779-28e1a12a-91e5-4bff-a14b-47eb424aeb21.png)

https://cleancookingalliance.org/

**Comment by dimasciput** [comment]
this is done
